require 'yard-dm/property_handler'
require 'yard-dm/has_handler'
require 'yard-dm/belongs_to_handler'
require 'yard-dm/legacy/property_handler'
require 'yard-dm/legacy/has_handler'
require 'yard-dm/legacy/belongs_to_handler'
